version: '3'

services:
  web2:
    image: nginx
    environment:
      - VIRTUAL_HOST=web2.localhost
    volumes:
      - ./config/web2/default.conf:/etc/nginx/conf.d/default.conf
      - ./web2:/var/www/html
networks:
  default:
    external:
      name: shared
