version: '3'

services:
  web1:
    image: nginx
    environment:
      - VIRTUAL_HOST=web1.localhost
    volumes:
      - ./config/web1/default.conf:/etc/nginx/conf.d/default.conf
      - ./web1:/var/www/html
networks:
  default:
    external:
      name: shared
